#!/usr/bin/env python3
"""Build the offline Webster's 1913 data files for omarchy-dictionary.

Downloads GCIDE XML 0.53 (if needed), parses the 26 letter files, and emits
one gzipped JSON file per starting letter into data/webster/:

    data/webster/a.json.gz ... z.json.gz, other.json.gz

Each file maps a normalized headword (lowercased, markup stripped) to::

    {"w": "Apple", "pr": "(ap'p'l)", "pos": [["n", ["def1", "def2"]], ...]}

`pos` groups preserve document order; definitions within a group are in
sense-number order. The panel numbers definitions itself, so sense numbers
are not stored.

Usage:
    scripts/build-webster.py [--zip PATH] [--out DIR]

The raw XML is never committed (see .gitignore); only the generated
data/webster/*.json.gz files are shipped. GCIDE's compiled dataset is
GPL — a license notice is written into data/webster/ by this script.
"""
import argparse
import gzip
import html
import json
import os
import re
import sys
import urllib.request
import zipfile
import xml.etree.ElementTree as ET

GCIDE_ZIP_URL = "http://www.ibiblio.org/webster/gcide_xml-0.53.zip"
GCIDE_ZIP_SHA_NOTE = "gcide_xml-0.53.zip (13.7 MiB, published 2022-08-09)"

LICENSE_NOTE = """\
Webster's 1913 dictionary data in this directory was derived from the
GNU Collaborative International Dictionary of English (GCIDE) XML 0.53,
which is published under the GNU General Public License (v3 or later).
The 1913 Webster's core text is public domain; the GPL covers GCIDE's
markup, volunteer edits, and WordNet-derived additions.

Source: http://www.ibiblio.org/webster/
License: https://www.gnu.org/licenses/gpl-3.0.html

These files were generated by scripts/build-webster.py and are build
artifacts — edit the script, not the data.
"""


def log(msg):
    print(msg, flush=True)


def ensure_zip(zip_path):
    if os.path.exists(zip_path):
        log("using existing %s" % zip_path)
        return
    log("downloading %s ..." % GCIDE_ZIP_URL)
    os.makedirs(os.path.dirname(zip_path) or ".", exist_ok=True)
    urllib.request.urlretrieve(GCIDE_ZIP_URL, zip_path)
    log("saved %s" % zip_path)


def load_entities(zf):
    """Extract <!ENTITY name 'value'> declarations from the root gcide.xml."""
    text = zf.read("gcide_xml-0.53/gcide.xml").decode("utf-8")
    decls = re.findall(r"<!ENTITY\s+(\S+)\s+'([^']*)'>", text)
    out = []
    for name, val in decls:
        if name in ("amp", "lt"):  # self-referential trick; skip
            continue
        out.append('<!ENTITY %s "%s">' % (name, val.replace('"', "")))
    log("loaded %d entity declarations" % len(out))
    return "\n".join(out)


def text_of(el):
    return "".join(el.itertext())


def clean(s):
    return html.unescape(re.sub(r"\s+", " ", s or "").strip())


def norm_key(hw):
    key = clean(hw).lower()
    key = re.sub(r"\s+", " ", key)
    return key


def bucket_for(key):
    if key and "a" <= key[0] <= "z":
        return key[0]
    return "other"


def parse_letter(zf, name, entities):
    frag = zf.read("gcide_xml-0.53/" + name).decode("utf-8")
    doc = ("<?xml version='1.0' encoding='utf-8'?>\n"
           "<!DOCTYPE root [\n" + entities + "\n]>\n<root>" + frag + "</root>")
    root = ET.fromstring(doc)

    entries = {}
    order = []
    cur = None
    last_pos = ""

    def new_entry(hw):
        nonlocal cur, last_pos
        key = norm_key(hw)
        if not key:
            cur = None
            return
        if key not in entries:
            entries[key] = {"w": clean(hw), "pr": "", "pos": []}
            order.append(key)
        cur = entries[key]
        last_pos = ""

    def add_group(pos, pr, defs):
        nonlocal last_pos
        if cur is None or not defs:
            return
        pos = clean(pos).rstrip(".")
        if not pos:
            pos = last_pos  # continuation block: inherit the entry's last pos
        if not pos:
            pos = ""  # entries that never declare a pos (letters, prefixes)
        if pr and not cur["pr"]:
            cur["pr"] = clean(pr)
        grp = None
        for g in cur["pos"]:
            if g[0].lower() == pos.lower():
                grp = g
                break
        if grp is None:
            grp = [pos, []]
            cur["pos"].append(grp)
        for d in defs:
            d = clean(d)
            if d and d not in grp[1]:
                grp[1].append(d)

    for p in root.iter("p"):
        ent = p.find("ent")
        if ent is not None and ent.text and ent.text.strip():
            new_entry(ent.text)
        if cur is None:
            continue
        pr = ""
        pre = p.find("pr")
        if pre is not None:
            pr = text_of(pre)
            if clean(pr) == "(?)":  # GCIDE's marker for unknown pronunciation
                pr = ""
        pos = ""
        pose = p.find("pos")
        if pose is not None:
            pos = text_of(pose)
        if clean(pos).rstrip("."):
            # Remember the entry's most recent part of speech even when this
            # block carries no definitions (e.g. "Abase": pos lives in the
            # first <p>, the <def>s in the second).
            last_pos = clean(pos).rstrip(".")
        defs = [text_of(d) for d in p.iter("def")]
        # <def> elements nested anywhere in the block, in document order
        add_group(pos, pr, defs)

    return [(k, entries[k]) for k in order
            if any(g[1] for g in entries[k]["pos"])]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--zip", default="/tmp/gcide/gcide_xml-0.53.zip")
    ap.add_argument("--out", default="data/webster")
    args = ap.parse_args()

    ensure_zip(args.zip)
    os.makedirs(args.out, exist_ok=True)

    buckets = {}
    total = 0
    with zipfile.ZipFile(args.zip) as zf:
        entities = load_entities(zf)
        for letter in [chr(c) for c in range(ord("a"), ord("z") + 1)]:
            name = "gcide_%s.xml" % letter
            parsed = parse_letter(zf, name, entities)
            for key, entry in parsed:
                b = bucket_for(key)
                buckets.setdefault(b, {})[key] = entry
            total += len(parsed)
            log("letter %s: %d headwords" % (letter, len(parsed)))

    total_gz = 0
    for b in sorted(buckets):
        raw = json.dumps(buckets[b], ensure_ascii=False,
                         separators=(",", ":")).encode("utf-8")
        gz = gzip.compress(raw, compresslevel=9)
        path = os.path.join(args.out, b + ".json.gz")
        with open(path, "wb") as f:
            f.write(gz)
        total_gz += len(gz)
        log("wrote %s: %d headwords, %.2f MiB gz"
            % (path, len(buckets[b]), len(gz) / 2**20))

    with open(os.path.join(args.out, "LICENSE-DATA.txt"), "w") as f:
        f.write(LICENSE_NOTE)

    log("total: %d headwords, %.2f MiB gzipped (%s)"
        % (total, total_gz / 2**20, GCIDE_ZIP_SHA_NOTE))


if __name__ == "__main__":
    main()
